# Generated by Django 2.2 on 2019-12-16 16:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('message', models.CharField(max_length=300, verbose_name='内容')),
                ('read', models.CharField(choices=[('0', '否'), ('1', '是')], max_length=300, verbose_name='是否阅读')),
                ('receive', models.ForeignKey(limit_choices_to={'user_id': '学生'}, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='receive', to='app.User', verbose_name='接收人')),
                ('sender', models.ForeignKey(limit_choices_to={'user_id': '教师'}, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='sender', to='app.User', verbose_name='发送人')),
            ],
            options={
                'verbose_name': '消息管理',
                'verbose_name_plural': '消息管理',
            },
        ),
    ]
